--CargoType Table
SET IDENTITY_INSERT [dbo].[CargoType] ON
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (1, N'General Freight')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (2, N'Household Goods')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (3, N'Metal: Sheets,Coils, Rolls')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (4, N'Motor Vehicles')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (6, N'Logs, Poles, Beams, Lumber')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (7, N'Building, Materials')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (8, N'Mobile Homes')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (9, N'Machinery, Large Objects')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (10, N'Fresh Produce')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (11, N'Liquids/Gases')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (12, N'Intermodal Containers')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (14, N'OilfieldEquipment')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (15, N'Livestock')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (16, N'Grain, Feed, Hay')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (17, N'Coal/Coke')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (18, N'Meat')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (20, N'U.S. Mail')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (21, N'Chemicals')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (22, N'Commodities Dry Bulk')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (23, N'Refrigerated Food')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (24, N'Beverages')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (25, N'Paper Products')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (26, N'Utility')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (27, N'Farm Supplies')
INSERT INTO [dbo].[CargoType] ([CargoNumber], [CargoName]) VALUES (28, N'Construction')
SET IDENTITY_INSERT [dbo].[CargoType] OFF

--serviceType Table
SET IDENTITY_INSERT [dbo].[ServiceType] ON
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (1, N'Vans')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (2, N'Flatbed')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (3, N'Reefer')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (4, N'Dry Bulk')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (5, N'Hazmat')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (6, N'Car Transport')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (7, N'Mobile Homes')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (8, N'Tankers')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (9, N'Intermodal ')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (10, N'Livestock')
INSERT INTO [dbo].[ServiceType] ([ServiceTypeNumber], [Service Type]) VALUES (11, N'Coal/Coke')
SET IDENTITY_INSERT [dbo].[ServiceType] OFF

--State Table
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Alabama', N'AL')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Alaska', N'AK')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Arizona', N'AZ')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Arkansas', N'AR')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'California', N'CA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Colorado', N'CO')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Connecticut', N'CT')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Delaware', N'DE')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Florida', N'FL')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Georgia', N'GA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Hawaii', N'HI')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Idaho', N'ID')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Illinois', N'IL')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Indiana', N'IN')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Iowa', N'IA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Kansas', N'KS')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Kentucky', N'KY')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Louisiana', N'LA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Maine', N'ME')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Maryland', N'MD')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Massachusetts', N'MA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Michigan', N'MI')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Minnesota', N'MN')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Mississippi', N'MS')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Missouri', N'MO')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Montana', N'MT')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Nebraska', N'NE')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Nevada', N'NV')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'New Hampshire', N'NH')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'New Jersey', N'NJ')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'New Mexico', N'NM')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'New York', N'NY')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'North Carolina', N'NC')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'North Dakota', N'ND')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Ohio', N'OH')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Oklahoma', N'OK')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Oregon', N'OR')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Pennsylvania', N'PA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Rhode Island', N'RI')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'South Carolina', N'SC')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'South Dakota', N'SD')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Tennessee', N'TN')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Texas', N'TX')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Utah', N'UT')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Vermont', N'VT')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Virginia', N'VA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Washington', N'WA')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Washington DC', N'DC')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'West Virginia', N'WV')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Wisconsin', N'WI')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'US', N'Wyoming', N'WY')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Alberta', N'AB')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'British Columbia', N'BC')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Manitoba', N'MB')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'New Brunswick', N'NB')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Newfoundland and Labrador', N'NL')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Nova Scotia', N'NS')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Northwest Territories', N'NT')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Nunavut', N'NU')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Ontario', N'ON')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Prince Edward Island', N'PE')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Quebec', N'QC')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Saskatchewan', N'SK')
INSERT INTO [dbo].[States] ([CountryCode], [State], [StateCode]) VALUES (N'CA', N'Yukon', N'YT')


--Admin Table
INSERT INTO [dbo].[Admin] ([HomePageTitle], [HomePageDescription], [StatePageTitle], [StatePageDescription], [CityPageTitle], [CityPageDescription]) VALUES (N'Trucking Companies, Freight Brokers, US, Canada. Van, Reefer, Flatbed, HazMat', N'The most comprehensive, up to date directory of US and Canadian Trucking Companies and Freight Brokers. Search by location, service type, cargo type, company size and much more. Use the map to define the area of your search. Let our unique algorithm suggest the best Trucking Company or Freight Broker that suits your needs. ', N' Trucking Companies, Freight Brokers. Van, Reefer, Flatbed, HazMat', N'most comprehensive, up to date directory of Trucking Companies and Freight Brokers. Search by location, service type, cargo type, company size and much more. Use the map to define the area of your search. Let our unique algorithm suggest the best Trucking Company or Freight Broker that suits your needs.', N'Trucking Companies, Freight Brokers. Van, Reefer, Flatbed, HazMat', N'most comprehensive, up to date directory of Trucking Companies and Freight Brokers. Search by location, service type, cargo type, company size and much more. Use the map to define the area of your search. Let our unique algorithm suggest the best Trucking Company or Freight Broker that suits your needs.')
