CREATE TABLE [dbo].[PreTransportCompany] (
    [Status]                                      NVARCHAR (255) NULL,
    [EntityType]                                  NVARCHAR (255) NULL,
    [USDOTNumber]                                 INT            NOT NULL,
    [LegalName]                                   NVARCHAR (255) NULL,
    [DoingBusinessAsName]                         NVARCHAR (255) NULL,
    [DunBradstreetNumber]                         NVARCHAR (255) NULL,
    [PhysicalAddressNationality]                  NVARCHAR (255) NULL,
    [PhysicalAddressFmcsaRegion]                  INT            NULL,
    [PhysicalAddressStreet]                       NVARCHAR (255) NULL,
    [PhysicalAddressCity]                         NVARCHAR (255) NULL,
    [PhysicalAddressCountyCode]                   INT            NULL,
    [PhysicalAddressStateCode]                    NVARCHAR (255) NULL,
    [PhysicalAddressZipCode]                      NVARCHAR (255) NULL,
    [UndeliverablePhysicalAddress]                NVARCHAR (255) NULL,
    [OfficeTelephoneNumber]                       NVARCHAR (255) NULL,
    [CellPhoneNumber]                             NVARCHAR (255) NULL,
    [OfficeFaxPhoneNumber]                        NVARCHAR (255) NULL,
    [MailingAddressNationality]                   NVARCHAR (255) NULL,
    [MailingAddressStreet]                        NVARCHAR (255) NULL,
    [MailingAddressCity]                          NVARCHAR (255) NULL,
    [MailingAddressCountyCode]                    INT            NULL,
    [MailingAddressStateCode]                     NVARCHAR (255) NULL,
    [MailingAddressZipCode]                       NVARCHAR (255) NULL,
    [UndeliverableMailingAddress]                 NVARCHAR (255) NULL,
    [OfficerInChargeCode]                         INT            NULL,
    [SafetyInvestigatorTerritoryCode]             NVARCHAR (255) NULL,
    [IccDocketNumber1Prefix]                      NVARCHAR (255) NULL,
    [IccDocketNumberFirst]                        NVARCHAR (255) NULL,
    [IccDocket2Prefix]                            NVARCHAR (255) NULL,
    [IccDocketNumberSecond]                       NVARCHAR (255) NULL,
    [IccDocket3Prefix]                            NVARCHAR (255) NULL,
    [IccDocketNumberThird]                        NVARCHAR (255) NULL,
    [Classification]                              NVARCHAR (255) NULL,
    [ClassificationOtherDefined]                  NVARCHAR (255) NULL,
    [OperationCarrierInterstate]                  NVARCHAR (255) NULL,
    [OperationCarrierIntrastateHazmat]            NVARCHAR (255) NULL,
    [OperationCarrierIntrastateNonHazmat]         NVARCHAR (255) NULL,
    [OperationShipperInterstate]                  NVARCHAR (255) NULL,
    [OperationShipperIntrastate]                  NVARCHAR (255) NULL,
    [OperationVehicleRegistrant]                  NVARCHAR (255) NULL,
    [BusinessOrganizationCode]                    NVARCHAR (255) NULL,
    [CargoTransportedAGeneralFreight]             NVARCHAR (255) NULL,
    [CargoTransportedBHouseholdGoods]             NVARCHAR (255) NULL,
    [CargoTransportedCMetalSheetsCoilsRolls]      NVARCHAR (255) NULL,
    [CargoTransportedDMotorVehicles]              NVARCHAR (255) NULL,
    [CargoTransportedEDriveawayTowaway]           NVARCHAR (255) NULL,
    [CargoTransportedFLogsPolesBeamsLumber]       NVARCHAR (255) NULL,
    [CargoTransportedGBuildingMaterials]          NVARCHAR (255) NULL,
    [CargoTransportedHMobileHomes]                NVARCHAR (255) NULL,
    [CargoTransportedIMachineryLargeObjects]      NVARCHAR (255) NULL,
    [CargoTransportedJFreshProduce]               NVARCHAR (255) NULL,
    [CargoTransportedKLiquidsGases]               NVARCHAR (255) NULL,
    [CargoTransportedLIintermodalContainers]      NVARCHAR (255) NULL,
    [CargoTransportedMPassengers]                 NVARCHAR (255) NULL,
    [CargoTransportedNOilfieldEquipment]          NVARCHAR (255) NULL,
    [CargoTransportedOLivestock]                  NVARCHAR (255) NULL,
    [CargoTransportedPGrainFeedHay]               NVARCHAR (255) NULL,
    [CargoTransportedQCoalCoke]                   NVARCHAR (255) NULL,
    [CargoTransportedRMeat]                       NVARCHAR (255) NULL,
    [CargoTransportedSGarbageRefuseTrash]         NVARCHAR (255) NULL,
    [CargoTransportedTUSMail]                     NVARCHAR (255) NULL,
    [CargoTransportedUChemicals]                  NVARCHAR (255) NULL,
    [CargoTransportedVCommoditiesDryBulk]         NVARCHAR (255) NULL,
    [CargoTransportedWRefrigeratedFood]           NVARCHAR (255) NULL,
    [CargoTransportedXBeverages]                  NVARCHAR (255) NULL,
    [CargoTransportedYPaperProducts]              NVARCHAR (255) NULL,
    [CargoTransportedZUtility]                    NVARCHAR (255) NULL,
    [CargoTransportedAAFarmSupplies]              NVARCHAR (255) NULL,
    [CargoTransportedBBConstruction]              NVARCHAR (255) NULL,
    [CargoTransportedCCWaterWell]                 NVARCHAR (255) NULL,
    [CargoTransportedDDOther]                     NVARCHAR (255) NULL,
    [CargoTransportedOtherDefined]                NVARCHAR (255) NULL,
    [HazmatIndicator]                             NVARCHAR (255) NULL,
    [NNEquipmentUnitsOwnedTruck]                  INT            NULL,
    [NNEquipmentUnitsOwnedTractor]                INT            NULL,
    [NNEquipmentUnitsOwnedTrailer]                INT            NULL,
    [NNEquipmentUnitsOwnedMotorCoach]             INT            NULL,
    [NNEquipmentUnitsOwnedSchoolBus1_8]           INT            NULL,
    [NNEquipmentUnitsOwnedSchoolBus9_15]          INT            NULL,
    [NNEquipmentUnitsOwnedSchoolBus16Plus]        INT            NULL,
    [NNEquipmentUnitsOwnedMiniBusVan16Plus]       INT            NULL,
    [NNEquipmentUnitsOwnedMiniBusVan1_8]          INT            NULL,
    [NNEquipmentUnitsOwnedMiniBusVan9_15]         INT            NULL,
    [NNEquipmentUnitsOwnedLimo1_8]                INT            NULL,
    [NNEquipmentUnitsOwnedLimo9_15]               INT            NULL,
    [NNEquipmentUnitsOwnedLimo16Plus]             INT            NULL,
    [NNEquipmentUnitsTermLeasedTruck]             INT            NULL,
    [NNEquipmentUnitsTermLeasedTractor]           INT            NULL,
    [NNEquipmentUnitsTermLeasedTrailer]           INT            NULL,
    [NNEquipmentUnitsTermLeasedMotorCoach]        INT            NULL,
    [NNEquipmentUnitsTermLeasedSchoolBus1_8]      INT            NULL,
    [NNEquipmentUnitsTermLeasedSchoolBus9_15]     INT            NULL,
    [NNEquipmentUnitsTermLeasedSchoolBus16Plus]   INT            NULL,
    [NNEquipmentUnitsTermLeasedMiniBusVan16Plus]  INT            NULL,
    [NNEquipmentUnitsTermLeasedMiniBusVan1_8]     INT            NULL,
    [NNEquipmentUnitsTermLeasedMiniBusVan9_15]    INT            NULL,
    [NNEquipmentUnitsTermLeasedLimo1_8]           INT            NULL,
    [NNEquipmentUnitsTermLeasedLimo9_15]          INT            NULL,
    [NNEquipmentUnitsTermLeasedLimo16Plus]        INT            NULL,
    [NNEquipmentUnitsTripLeasedTruck]             INT            NULL,
    [NNEquipmentUnitsTripLeasedTractor]           INT            NULL,
    [NNEquipmentUnitsTripLeasedTrailer]           INT            NULL,
    [NNEquipmentUnitsTripLeasedMotorCoach]        INT            NULL,
    [NNEquipmentUnitsTripLeasedSchoolBus1_8]      INT            NULL,
    [NNEquipmentUnitsTripLeasedSchoolBus9_15]     INT            NULL,
    [NNEquipmentUnitsTripLeasedSchoolBus16Plus]   INT            NULL,
    [NNEquipmentUnitsTripLeasedMiniBusVan16Plus]  INT            NULL,
    [NNEquipmentUnitsTripLeasedMiniBusVan1_8]     INT            NULL,
    [NNEquipmentUnitsTripLeasedMiniBusVan9_15]    INT            NULL,
    [NNEquipmentUnitsTripLeasedLimo1_8]           INT            NULL,
    [NNEquipmentUnitsTripLeasedLimo9_15]          INT            NULL,
    [NNEquipmentUnitsTripLeasedLimo16Plus]        INT            NULL,
    [TotalNumberOfTrucks]                         INT            NULL,
    [TotalNumberOfBuses]                          INT            NULL,
    [TotalNumberOfPowerUnits]                     INT            NULL,
    [FleetSizeCode]                               NVARCHAR (255) NULL,
    [NNDriversInterstateWithin100Miles]           NVARCHAR (255) NULL,
    [NNDriversInterstateBeyond100Miles]           NVARCHAR (255) NULL,
    [NNDriversInterstateTotal]                    INT            NULL,
    [NNDriversIntrastateWithin100Miles]           NVARCHAR (255) NULL,
    [NNDriversIntrastateBeyond100Miles]           NVARCHAR (255) NULL,
    [NNDriversIntrastateTotal]                    INT            NULL,
    [NNDriversAvgNumberTripLeasedDriversPerMonth] NVARCHAR (255) NULL,
    [NNDriversGrandTotalInterstateAndIntrastate]  NVARCHAR (255) NULL,
    [NNDriversTotalWithCommercialDriversLicense]  NVARCHAR (255) NULL,
    [LatestReviewType]                            NVARCHAR (255) NULL,
    [LatestReviewDocumentNN]                      NVARCHAR (255) NULL,
    [LatestReviewDate]                            NVARCHAR (255) NULL,
    [RecordableAccidentRate]                      NVARCHAR (255) NULL,
    [PreventableRecordableAccidentRate]           NVARCHAR (255) NULL,
    [MileageCalendarYearMCS_150]                  INT            NULL,
    [ReviewMileageMCS_151]                        NVARCHAR (255) NULL,
    [SafetyRatingTypeCode]                        NVARCHAR (255) NULL,
    [SafetyRatingEffectiveDate]                   NVARCHAR (255) NULL,
    [MexicanNeighborhoodPhysical]                 NVARCHAR (255) NULL,
    [MexicanNeighborhoodMailing]                  NVARCHAR (255) NULL,
    [McsipStep]                                   NVARCHAR (255) NULL,
    [McsipDate]                                   NVARCHAR (255) NULL,
    [UserId]                                      NVARCHAR (255) NULL,
    [ReasonCodeAdd]                               INT            NULL,
    [ReasonCodeChange]                            NVARCHAR (255) NULL,
    [ReasonCodeDelete]                            NVARCHAR (255) NULL,
    [Mcs_150MileageYear]                          NVARCHAR (255) NULL,
    [DateAdded]                                   INT            NULL,
    [DateLastChanged]                             INT            NULL,
    [DateDeleted]                                 NVARCHAR (255) NULL,
    [TotalCars]                                   INT            NULL,
    [Version]                                     NVARCHAR (255) NULL,
    [CreationDate]                                INT            NULL,
    [AddUserId]                                   NVARCHAR (255) NULL,
    [DeleteUserId]                                NVARCHAR (255) NULL,
    [Mcs_150Date]                                 NVARCHAR (255) NULL,
    [RecordUpdatedFlag]                           INT            NULL,
    [EmailAddress]                                NVARCHAR (255) NULL,
    [UsdotRevokedFlag]                            NVARCHAR (255) NULL,
    [UsdotRevokedNumber]                          NVARCHAR (255) NULL,
    [CompanyRepresentativeOne]                    NVARCHAR (255) NULL,
    [CompanyRepresentativeTwo]                    NVARCHAR (255) NULL
);

