//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public byte RoleId { get; set; }
        public bool IsActive { get; set; }
        public string ForgotPasswordKey { get; set; }
        public Nullable<System.Guid> ActivationKey { get; set; }
        public bool IsDataMigrationLogEnabled { get; set; }
    }
}
