//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Business()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int USDOTNumber { get; set; }
        public string Website { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public Nullable<bool> WebsiteApproved { get; set; }
        public Nullable<bool> CommunicationApproved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.Guid> VerificationKey { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string BusinessContactEmail { get; set; }
        public string JobContactEmail { get; set; }
        public string JobContactPhone { get; set; }
        public string JobContactSMS { get; set; }
        public bool NowHiring { get; set; }
        public string ForgotPasswordKey { get; set; }
        public Nullable<int> InvalidLoginAttempt { get; set; }
    
        public virtual TransportCompany TransportCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
