//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carrier()
        {
            this.Carrier_LoadType = new HashSet<Carrier_LoadType>();
            this.Carrier_State_From = new HashSet<Carrier_State_From>();
            this.Carrier_State_To = new HashSet<Carrier_State_To>();
            this.QuoteSents = new HashSet<QuoteSent>();
        }
    
        public int Id { get; set; }
        public Nullable<int> USDOTNumber { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson1 { get; set; }
        public string ContactEmail1 { get; set; }
        public string ContactPhone1 { get; set; }
        public string ContactPerson2 { get; set; }
        public string ContactEmail2 { get; set; }
        public string ContactPhone2 { get; set; }
        public bool CarrierActive { get; set; }
        public string Website { get; set; }
        public Nullable<int> MaxQuotesPerMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrier_LoadType> Carrier_LoadType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrier_State_From> Carrier_State_From { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrier_State_To> Carrier_State_To { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteSent> QuoteSents { get; set; }
    }
}
