//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public string CountryCode { get; set; }
        public string StateCode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> NumberOfCompanies { get; set; }
        public string Article { get; set; }
        public Nullable<bool> CityArticleAllowed { get; set; }
    }
}
