//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailsSent
    {
        public int USDOTNumber { get; set; }
        public int EmailID { get; set; }
        public System.DateTime SentDate { get; set; }
    
        public virtual Email Email { get; set; }
        public virtual TransportCompany TransportCompany { get; set; }
    }
}
