//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int Id { get; set; }
        public string GoodsDescription { get; set; }
        public Nullable<int> LoadStatusTypeId { get; set; }
        public Nullable<int> NoOfContainers { get; set; }
        public Nullable<int> LoadContainerTypeId { get; set; }
        public Nullable<int> NoOfItems { get; set; }
        public Nullable<int> LoadItemTypeId { get; set; }
        public Nullable<int> DimentionLength { get; set; }
        public Nullable<int> DimentionWidth { get; set; }
        public Nullable<int> DimentionHeight { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<int> LoadTruckTypeId { get; set; }
        public Nullable<int> LoadInfoId { get; set; }
        public Nullable<int> LoadClassId { get; set; }
        public Nullable<bool> IsHasmat_ { get; set; }
        public Nullable<bool> IsNonStackable_ { get; set; }
    
        public virtual LoadClass LoadClass { get; set; }
        public virtual LoadContainerLength LoadContainerLength { get; set; }
        public virtual LoadInfo LoadInfo { get; set; }
        public virtual LoadItemType LoadItemType { get; set; }
        public virtual LoadContainerType LoadContainerType { get; set; }
        public virtual LoadTruckType LoadTruckType { get; set; }
    }
}
