//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundBanner
    {
        public long Id { get; set; }
        public byte PageLevel { get; set; }
        public bool IsShow { get; set; }
        public string OriginalFileName { get; set; }
        public string FileName { get; set; }
        public string URL { get; set; }
        public bool IsFollow { get; set; }
        public string AltText { get; set; }
        public string TitleText { get; set; }
    }
}
