//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartnerCarrier_DevEntities : DbContext
    {
        public PartnerCarrier_DevEntities()
            : base("name=PartnerCarrier_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<CargoType> CargoTypes { get; set; }
        public virtual DbSet<Carrier_LoadType> Carrier_LoadType { get; set; }
        public virtual DbSet<Carrier_State_From> Carrier_State_From { get; set; }
        public virtual DbSet<Carrier_State_To> Carrier_State_To { get; set; }
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<DbVersion> DbVersions { get; set; }
        public virtual DbSet<DbVersionHistory> DbVersionHistories { get; set; }
        public virtual DbSet<DeletedRecord> DeletedRecords { get; set; }
        public virtual DbSet<DriverType> DriverTypes { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailsSent> EmailsSents { get; set; }
        public virtual DbSet<GetAQuoteToShow> GetAQuoteToShows { get; set; }
        public virtual DbSet<LoadClass> LoadClasses { get; set; }
        public virtual DbSet<LoadContainerLength> LoadContainerLengths { get; set; }
        public virtual DbSet<LoadContainerType> LoadContainerTypes { get; set; }
        public virtual DbSet<LoadInfo> LoadInfoes { get; set; }
        public virtual DbSet<LoadItemType> LoadItemTypes { get; set; }
        public virtual DbSet<LoadTruckType> LoadTruckTypes { get; set; }
        public virtual DbSet<LoadType> LoadTypes { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<Quote_SpecialHandling_Location> Quote_SpecialHandling_Location { get; set; }
        public virtual DbSet<QuoteRefrigeration> QuoteRefrigerations { get; set; }
        public virtual DbSet<QuoteSent> QuoteSents { get; set; }
        public virtual DbSet<QuoteTemperature> QuoteTemperatures { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<SpecialHandling> SpecialHandlings { get; set; }
        public virtual DbSet<TrailerType> TrailerTypes { get; set; }
        public virtual DbSet<TransportCompany> TransportCompanies { get; set; }
        public virtual DbSet<PreTransportCompany> PreTransportCompanies { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Load> Loads { get; set; }
        public virtual DbSet<OutboundLink> OutboundLinks { get; set; }
        public virtual DbSet<OutboundBanner> OutboundBanners { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ReviewReply> ReviewReplies { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
    }
}
