//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quote()
        {
            this.Quote_SpecialHandling_Location = new HashSet<Quote_SpecialHandling_Location>();
            this.QuoteSents = new HashSet<QuoteSent>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string OriginURL { get; set; }
        public string ShipperFirstName { get; set; }
        public string ShipperLastName { get; set; }
        public string ShipperEmail { get; set; }
        public string ShipperPhone { get; set; }
        public string ShipperCompanyName { get; set; }
        public string FromState { get; set; }
        public string FromCity { get; set; }
        public string ToState { get; set; }
        public string ToCity { get; set; }
        public int LoadTypeId { get; set; }
        public System.DateTime PickupDate { get; set; }
        public Nullable<int> RefrigerationId { get; set; }
        public Nullable<int> TemperatureId { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<int> FromLocationTypeId { get; set; }
        public Nullable<int> ToLocationTypeId { get; set; }
        public string LoadDetailDescription { get; set; }
        public Nullable<bool> IsFlexible { get; set; }
    
        public virtual LoadType LoadType { get; set; }
        public virtual LocationType LocationType { get; set; }
        public virtual LocationType LocationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote_SpecialHandling_Location> Quote_SpecialHandling_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuoteSent> QuoteSents { get; set; }
        public virtual QuoteRefrigeration QuoteRefrigeration { get; set; }
        public virtual QuoteTemperature QuoteTemperature { get; set; }
    }
}
