//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote_SpecialHandling_Location
    {
        public int Id { get; set; }
        public int QuoteId { get; set; }
        public int SpecialHandlingId { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
