//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteSent
    {
        public int Id { get; set; }
        public int QuoteID { get; set; }
        public int CarrierId { get; set; }
        public System.DateTime SentDate { get; set; }
    
        public virtual Carrier Carrier { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
