//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewReply
    {
        public int Id { get; set; }
        public int ReviewId { get; set; }
        public int CompanyUSDOT { get; set; }
        public string ReplyText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual TransportCompany TransportCompany { get; set; }
        public virtual Review Review { get; set; }
    }
}
