//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialHandling
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public Nullable<int> LocationTypeId { get; set; }
        public Nullable<int> LoadTypeId { get; set; }
    
        public virtual LoadType LoadType { get; set; }
        public virtual LocationType LocationType { get; set; }
    }
}
