//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerCarrier.Infrastructure.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransportCompany()
        {
            this.EmailsSents = new HashSet<EmailsSent>();
            this.CargoTypes = new HashSet<CargoType>();
            this.DriverTypes = new HashSet<DriverType>();
            this.ServiceTypes = new HashSet<ServiceType>();
            this.TrailerTypes = new HashSet<TrailerType>();
            this.ReviewReplies = new HashSet<ReviewReply>();
            this.Reviews = new HashSet<Review>();
        }
    
        public string Status { get; set; }
        public string EntityType { get; set; }
        public int USDOTNumber { get; set; }
        public string LegalName { get; set; }
        public string DoingBusinessAsName { get; set; }
        public string DunBradstreetNumber { get; set; }
        public string PhysicalAddressNationality { get; set; }
        public Nullable<int> PhysicalAddressFmcsaRegion { get; set; }
        public string PhysicalAddressStreet { get; set; }
        public string PhysicalAddressCity { get; set; }
        public Nullable<int> PhysicalAddressCountyCode { get; set; }
        public string PhysicalAddressStateCode { get; set; }
        public string PhysicalAddressZipCode { get; set; }
        public string UndeliverablePhysicalAddress { get; set; }
        public string OfficeTelephoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string OfficeFaxPhoneNumber { get; set; }
        public string MailingAddressNationality { get; set; }
        public string MailingAddressStreet { get; set; }
        public string MailingAddressCity { get; set; }
        public Nullable<int> MailingAddressCountyCode { get; set; }
        public string MailingAddressStateCode { get; set; }
        public string MailingAddressZipCode { get; set; }
        public string UndeliverableMailingAddress { get; set; }
        public Nullable<int> OfficerInChargeCode { get; set; }
        public string SafetyInvestigatorTerritoryCode { get; set; }
        public string IccDocketNumber1Prefix { get; set; }
        public Nullable<int> IccDocketNumberFirst { get; set; }
        public string IccDocket2Prefix { get; set; }
        public string IccDocketNumberSecond { get; set; }
        public string IccDocket3Prefix { get; set; }
        public string IccDocketNumberThird { get; set; }
        public string Classification { get; set; }
        public string ClassificationOtherDefined { get; set; }
        public string OperationCarrierInterstate { get; set; }
        public string OperationCarrierIntrastateHazmat { get; set; }
        public string OperationCarrierIntrastateNonHazmat { get; set; }
        public string OperationShipperInterstate { get; set; }
        public string OperationShipperIntrastate { get; set; }
        public string OperationVehicleRegistrant { get; set; }
        public string BusinessOrganizationCode { get; set; }
        public string CargoTransportedAGeneralFreight { get; set; }
        public string CargoTransportedBHouseholdGoods { get; set; }
        public string CargoTransportedCMetalSheetsCoilsRolls { get; set; }
        public string CargoTransportedDMotorVehicles { get; set; }
        public string CargoTransportedEDriveawayTowaway { get; set; }
        public string CargoTransportedFLogsPolesBeamsLumber { get; set; }
        public string CargoTransportedGBuildingMaterials { get; set; }
        public string CargoTransportedHMobileHomes { get; set; }
        public string CargoTransportedIMachineryLargeObjects { get; set; }
        public string CargoTransportedJFreshProduce { get; set; }
        public string CargoTransportedKLiquidsGases { get; set; }
        public string CargoTransportedLIintermodalContainers { get; set; }
        public string CargoTransportedMPassengers { get; set; }
        public string CargoTransportedNOilfieldEquipment { get; set; }
        public string CargoTransportedOLivestock { get; set; }
        public string CargoTransportedPGrainFeedHay { get; set; }
        public string CargoTransportedQCoalCoke { get; set; }
        public string CargoTransportedRMeat { get; set; }
        public string CargoTransportedSGarbageRefuseTrash { get; set; }
        public string CargoTransportedTUSMail { get; set; }
        public string CargoTransportedUChemicals { get; set; }
        public string CargoTransportedVCommoditiesDryBulk { get; set; }
        public string CargoTransportedWRefrigeratedFood { get; set; }
        public string CargoTransportedXBeverages { get; set; }
        public string CargoTransportedYPaperProducts { get; set; }
        public string CargoTransportedZUtility { get; set; }
        public string CargoTransportedAAFarmSupplies { get; set; }
        public string CargoTransportedBBConstruction { get; set; }
        public string CargoTransportedCCWaterWell { get; set; }
        public string CargoTransportedDDOther { get; set; }
        public string CargoTransportedOtherDefined { get; set; }
        public string HazmatIndicator { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedTruck { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedTractor { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedTrailer { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedMotorCoach { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedSchoolBus1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedSchoolBus9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedSchoolBus16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedMiniBusVan16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedMiniBusVan1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedMiniBusVan9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedLimo1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedLimo9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsOwnedLimo16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedTruck { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedTractor { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedTrailer { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedMotorCoach { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedSchoolBus1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedSchoolBus9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedSchoolBus16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedMiniBusVan16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedMiniBusVan1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedMiniBusVan9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedLimo1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedLimo9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsTermLeasedLimo16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedTruck { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedTractor { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedTrailer { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedMotorCoach { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedSchoolBus1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedSchoolBus9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedSchoolBus16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedMiniBusVan16Plus { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedMiniBusVan1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedMiniBusVan9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedLimo1_8 { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedLimo9_15 { get; set; }
        public Nullable<int> NNEquipmentUnitsTripLeasedLimo16Plus { get; set; }
        public Nullable<int> TotalNumberOfTrucks { get; set; }
        public Nullable<int> TotalNumberOfBuses { get; set; }
        public Nullable<int> TotalNumberOfPowerUnits { get; set; }
        public string FleetSizeCode { get; set; }
        public string NNDriversInterstateWithin100Miles { get; set; }
        public string NNDriversInterstateBeyond100Miles { get; set; }
        public Nullable<int> NNDriversInterstateTotal { get; set; }
        public string NNDriversIntrastateWithin100Miles { get; set; }
        public string NNDriversIntrastateBeyond100Miles { get; set; }
        public Nullable<int> NNDriversIntrastateTotal { get; set; }
        public string NNDriversAvgNumberTripLeasedDriversPerMonth { get; set; }
        public Nullable<int> NNDriversGrandTotalInterstateAndIntrastate { get; set; }
        public string NNDriversTotalWithCommercialDriversLicense { get; set; }
        public string LatestReviewType { get; set; }
        public string LatestReviewDocumentNN { get; set; }
        public string LatestReviewDate { get; set; }
        public string RecordableAccidentRate { get; set; }
        public string PreventableRecordableAccidentRate { get; set; }
        public Nullable<int> MileageCalendarYearMCS_150 { get; set; }
        public string ReviewMileageMCS_151 { get; set; }
        public string SafetyRatingTypeCode { get; set; }
        public string SafetyRatingEffectiveDate { get; set; }
        public string MexicanNeighborhoodPhysical { get; set; }
        public string MexicanNeighborhoodMailing { get; set; }
        public string McsipStep { get; set; }
        public string McsipDate { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ReasonCodeAdd { get; set; }
        public string ReasonCodeChange { get; set; }
        public string ReasonCodeDelete { get; set; }
        public string Mcs_150MileageYear { get; set; }
        public Nullable<int> DateAdded { get; set; }
        public Nullable<int> DateLastChanged { get; set; }
        public string DateDeleted { get; set; }
        public Nullable<int> TotalCars { get; set; }
        public string Version { get; set; }
        public Nullable<int> CreationDate { get; set; }
        public string AddUserId { get; set; }
        public string DeleteUserId { get; set; }
        public string Mcs_150Date { get; set; }
        public Nullable<int> RecordUpdatedFlag { get; set; }
        public string EmailAddress { get; set; }
        public string UsdotRevokedFlag { get; set; }
        public string UsdotRevokedNumber { get; set; }
        public string CompanyRepresentativeOne { get; set; }
        public string CompanyRepresentativeTwo { get; set; }
        public Nullable<int> TrucksAndTractors { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> SortRelevance { get; set; }
        public string CompanyName { get; set; }
    
        public virtual Business Business { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailsSent> EmailsSents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargoType> CargoTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverType> DriverTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceType> ServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrailerType> TrailerTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewReply> ReviewReplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
